### ISSUE TITLE
could not open project file

### ISSUE THREAD

**Issue by zengyun-programmer** [truebit/xUnique#16]
After execute the command directly
```
python -mxUnique myProject.xcodeproj
```
I could not open my project again

![monosnap 2015-01-16 11-15-30](https://cloud.githubusercontent.com/assets/1861712/5771098/5796f5a4-9d71-11e4-912e-66ca0a88340c.jpg)

**Comment by truebit** [comment]
Could you please send me you original project.pbproj file privately?

**Comment by truebit** [comment]
Fixed in 5791ab7cef86fab18434d4c9efc12902a74959b5.
This bug is because PBXTarget has the same MD5 with another PBXGroup.
Now I have changed the rule of generating MD5. This will cause old version generated project file all change.
