### ISSUE TITLE
Missing semicolon in readme

### ISSUE THREAD

**Issue by JanNash** [truebit/xUnique#20]
I think it should be  
`{ echo '#!/bin/sh'; echo 'python2 -mxUnique path/to/MyProject.xcodeproj'; echo 'python2 -mxUnique path/to/Pods.xcodeproj'; } > .git/hooks/pre-commit`  
instead of  
`{ echo '#!/bin/sh'; echo 'python2 -mxUnique path/to/MyProject.xcodeproj'; echo 'python2 -mxUnique path/to/Pods.xcodeproj' } > .git/hooks/pre-commit`  

(Missing semicolon after `Pods.xcodeproj'`)

Apart from that, great project, Kudos!

**Comment by truebit** [comment]
I tried on zsh, it works. But on bash it does not work.
Thanks for your remind, I will fix that😁
