### ISSUE TITLE
Script run error

### ISSUE THREAD

**Issue by richarddigifit** [truebit/xUnique#23]
Hi I get the following error when I try to run your script:

    : command not foundk/Desktop/IOS: line 1: ?PNG
    /Users/myusername/Desktop/IOS: line 2: : command not found
    /Users/myusername/Desktop/IOS: line 6: syntax error near unexpected token `)'
    /Users/myusername/Desktop/IOS: line 6: `?@n.?z(7҇`$NOWfPȀe%f?????M]?_???^?^Ս??)
                                                                                 ??o?0???RLРxh????f2?Z+???V?M?ݬz??{z\<?e=?\??dĖ?Ue???<?{???????C_+?Is;???*?I[?R9?'?M????
    ??9a'Fǔ?.i$??2SSE???8???'

I think it has something to do with that my project file includes files from directorys that contain a space, for example Im using files from "/Users/myusername/Desktop/IOS Development/...."

**Comment by truebit** [comment]
When you use a dir with spaces in shell, you should either applying double quotes to the dir or applying backslash before the space char.




Please give it a try.



—

**Comment by richarddigifit** [comment]
Yea but its something in the zunique script, nothing I can do about that?

**Comment by truebit** [comment]
please add `-v` in the command, and paste the whole output here.



—

**Comment by truebit** [comment]
@richarddigifit please add more details for this issue, the infomation you provided is too hard to address the problem.

**Comment by richarddigifit** [comment]
can't reproduce it anymore, don't know what happened, script runs fine now...
