### ISSUE TITLE
How revert the changes from xUnique

### ISSUE THREAD

**Issue by cepages** [truebit/xUnique#30]
Hi 

Great tool, I'm testing a bit and I think it's really cool.

I want to use it, but I'm a bit afraid that Apple releases in a close future something to deal with the same problem and we need to revert the effect of this tool, so my question is:

How can we revert the effect of this tool so I can force to XCode to regenerate the UDID created initially?

Thanks

**Comment by truebit** [comment]
Maybe you should run xunique in debug mode the very first time, and save the `debug.json` file that records all the mappings of the original UUID and modified MD5.
And every time you added entries to the project, you should maintain that file to append new mappings to the file.
It's kind of troulesome though

**Comment by cepages** [comment]
I guess there is a away to convert that json file to the project file again (with the UDID's) o I will have to do it manually?

**Comment by truebit** [comment]
You can write a script to search and replace the MD5 with the original UUID in the project file, via the mappings in `debug.json`
