### ISSUE TITLE
Property List error

### ISSUE THREAD

**Issue by jeffctown** [truebit/xUnique#32]
Hey there.  I think this project sounds like a HUGE time saver, so I am excited to try it out.  I am trying to investigate how it works, but am not able to open my Xcode project after running xUnique the first time.

My project uses Cocoapods (/Pods is saved in the repo), but I have even tried removing the /Pods folder from the repo to make sure that wasn't the problem.  

I run xunique on my xcodeproj folder, and it does lists some files that were removed since they are either unused or duplicates, which is great.  After I open up my workspace in Xcode afterwords, it cannot read my project anymore.

- I'm using Xcode 7.3.1 on OSX 10.11.4
- I have Xcode command line tools installed
- plutil is accessible and in my $PATH
- My project works fine before using xUnique

**Here is what I did in my Terminal:**
<img width="1437" alt="xuniquefailure" src="https://cloud.githubusercontent.com/assets/2142301/15095121/10b4a24c-1487-11e6-84f7-92fecbcb65be.png">

**This is the error I get in Xcode after:**
<img width="258" alt="xcodefailure" src="https://cloud.githubusercontent.com/assets/2142301/15095120/0b8212e6-1487-11e6-827b-af44e5d09a01.png">

**The error I receive after trying xunique the second time is this:**

Property List error: Unexpected character / at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set.

Please check:
1. You have installed Xcode Command Line Tools and command 'plutil' could be found in $PATH;
2. The project file is not broken, such like merge conflicts, incomplete content due to xUnique failure. 

**Can anyone give me any tips on what I can do to fix this? **

UPDATE: By trying different command line flags, I have narrowed this down to using the -u flag in xunique.  If I use -s or -p I am able to run xunique a second time and open the project in Xcode.

**Comment by truebit** [comment]
It seems that some of your project file structure was incorrect?
According to the snapshot you posted, The line of `???SignInBenefitsBulletViews.xib` were deleted ,but the format of this line ends with only one `{` without any content. You should check the before and after lines of this line to see what's the point.

**Comment by truebit** [comment]
It seems that some of your project file structure was incorrect?
According to the snapshot you posted, The line of `???SignInBenefitsBulletViews.xib` were deleted ,but the format of this line ends with only one `{` without any content. You should check the before and after lines of this line to see what's the point.

**Comment by jeffctown** [comment]
That was it!  

That XIB didn't show up at all in my project strangely enough.  I had to look at the pbxproj file in a text editor to see it, and the reference was an absolute file reference from a develop who worked with us 5 years ago.  I deleted all references to this file inside of my pbxproj and everything is working great now.  

Thank you!

**Comment by truebit** [comment]
Glad it helps :smile:  
I think we may need more hint when delete a section. I would add the section delete warning sometime.
