### ISSUE TITLE
File 'project.pbxproj' is broken. Cannot find PBXProject name.

### ISSUE THREAD

**Issue by palexs** [truebit/xUnique#34]
The script I use is:
echo "Running xUnique..."
xunique "${PROJECT_FILE_PATH}/project.pbxproj"
xunique "${PODS_ROOT}/Pods.xcodeproj/project.pbxproj"

When added as a build phase the error for Pods.xcodeproj/project.pbxproj is:
"File 'project.pbxproj' is broken. Cannot find PBXProject name."

When added as the scheme's post build step it ignores Pod.xcodeproj/project.pbxproj completely and doesn't change identifiers.

**Comment by truebit** [comment]
I suggest using as git hook. Many issues reported that other methods would fail due to project file changing in progress by Xcode and/or cocoapods

Sent from my mobile device.

**Comment by palexs** [comment]
@truebit thanks for prompt reply!

**Comment by palexs** [comment]
@truebit I've tried using pre-commit hook, but I still get the same error. It seems like Pods.xcodeproj/project.pbxproj has different structure in comparison with MyProject.xcodeproj/project.pbxproj:

MyProject.xcodeproj/project.pbxproj:
/* Begin PBXProject section */
		6AE1FE371486FDD200743640 /* Project object */ = {
			isa = PBXProject;
			attributes = {
                        ...
                        }
/* End PBXProject section */

Pods.xcodeproj/project.pbxproj:
                        <key>isa</key>
			<string>PBXProject</string>

**Comment by truebit** [comment]
Ah I know. Cocoapods would convert project file to XML format by default. check [this link](https://github.com/CocoaPods/CocoaPods/wiki/Generate-ASCII-format-xcodeproj)
Maybe you need to convert it back to ASCII format.

**Comment by palexs** [comment]
@truebit that's exactly what I've been looking for! Thanks a lot!
