### ISSUE TITLE
Xcode project does not open after running xunique

### ISSUE THREAD

**Issue by chrisharrison** [truebit/xUnique#39]
After running `xunique <project>` Xcode can no longer open the project.

I can provide a diff of the file, or the original file.

**Comment by truebit** [comment]
please send me the original file. My Email could be found in source file.

Sent from my mobile device.

**Comment by chrisharrison** [comment]
Thanks @truebit I've sent you the file.

Incidentally, I managed to solve the issue. I've attached the commit of what I did to the previous file in order to get it to work with xunique.
[commit.txt](https://github.com/truebit/xUnique/files/821081/commit.txt)

**Comment by truebit** [comment]
That's great. But according to the diff and the source file, I cannot find the root cause. 
Could you please explain a little? Is this the xunique problem or the project file issue?

**Comment by brockboland** [comment]
I'm seeing something similar, but unfortunately, I don't believe I can share the project file in this case. I tried using the post-build action, and it works on the first build, but the second time, xUnique strips out a bunch of stuff it shouldn't and Xcode can no longer open the project file.

**Comment by truebit** [comment]
could you please paste your log output with option -v for its first time?
Sent from my mobile device.

**Comment by truebit** [comment]
Close due to no response for a long time
