### ISSUE TITLE
xunique homework.xcodeproj/project.pbxproj fail

### ISSUE THREAD

**Issue by iFengWang** [truebit/xUnique#40]
I Run ‘xunique homework.xcodeproj/project.pbxproj’ after return below info:

homework.xcodeproj/project.pbxproj: Property List error: Unexpected character / at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set.

Please check:
1. You have installed Xcode Command Line Tools and command 'plutil' could be found in $PATH;
2. The project file is not broken, such like merge conflicts, incomplete content due to xUnique failure.

**Comment by truebit** [comment]
Did you checked the list it reported?
Questions without attempt or circumstance description cannot be located
