### ISSUE TITLE
how to run xunique on non Mac OS X systems?

### ISSUE THREAD

**Issue by privateOmega** [truebit/xUnique#41]
```Traceback (most recent call last):
  File "/usr/local/bin/xunique", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/xUnique.py", line 543, in main
    xunique = XUnique(xcode_proj_path, options.verbose)
  File "/usr/local/lib/python2.7/dist-packages/xUnique.py", line 105, in __init__
    self.proj_json = self.pbxproj_to_json()
  File "/usr/local/lib/python2.7/dist-packages/xUnique.py", line 128, in pbxproj_to_json
    json_unicode_str = decoded_string(sp_co(pbproj_to_json_cmd))
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I have referenced the file using git hook.

**Comment by truebit** [comment]
“No such file or directory”, it seems that you did not install `Xcode Command Line Tools`. and make sure 'plutil' could be found in $PATH;

**Comment by privateOmega** [comment]
@truebit Well I am unable to do so, since I am running xUnique on my ubuntu and I don't have access to a mac. I have encountered git merge conflict on project.pbxproj file while upgrading my react-native app.

**Comment by truebit** [comment]
After some searching , [biplist](https://bitbucket.org/wooster/biplist) maybe the only one tool to convert plist binary file to json in linux.

You could adapt `pbxproj_to_json` method to use biplist instead of plutil.

**Comment by privateOmega** [comment]
@truebit Does this mean I have to alter the source code to change to biplist and build on my own from source?

**Comment by truebit** [comment]
Yes. writing a xcode project in non Mac OS X sytems is a very rare case after all.

**Comment by privateOmega** [comment]
Well all I tried to do was to generate a react-native app. Hell Hath no fury.

**Comment by truebit** [comment]
After some trial, I found that there is no tool in linux to parse `.pbxproj` file (a.k.a old-style NeXT ASCII format). all tools are for [modern property list file](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/PropertyList.html)

So xunique could NOT be supported in Linux

**Comment by privateOmega** [comment]
Oh well I guess I have no way out of this mess. Is it possible for you to remove conflicts in my `.pbxproj` file

**Comment by truebit** [comment]
Please post a question on Stackoverflow or react-native disscussion channel

**Comment by privateOmega** [comment]
haha. well highly unlikely in my school. Will try anyways :D
