### ISSUE TITLE
你好，我这里终端运行之后出现decode错误

### ISSUE THREAD

**Issue by DreamParagon** [truebit/xUnique#43]
终端运行sudo python -mxUnique XXX.xcodeproj，然后出现以下描述
<img width="571" alt="2017-05-12 12 57 34" src="https://cloud.githubusercontent.com/assets/5466178/25982869/a54069ce-3712-11e7-8ef5-8c0f88237e3d.png">
问题背景是我这个项目的原因是打不开，原因是
<img width="423" alt="2017-05-12 1 00 25" src="https://cloud.githubusercontent.com/assets/5466178/25982901/fde1c9e2-3712-11e7-920c-c952b2ed4a4b.png">
我对Python不懂，感谢您的帮助

**Comment by truebit** [comment]
你项目文件本身就有问题还是执行了xunique之后出现的问题？

xcodeproj文件本来就应该是utf8编码的，如果用utf8无法解码，那你的项目文件有问题

Sent from my mobile device.

**Comment by DreamParagon** [comment]
是这样的，我的项目无法打开，如问题中所示，我Google之后，查到疑似冲突，找到您的这个解决方案，安装并运行终端执行xunique之后发现这个问题，因为项目打不开，Google给出的信息有限，所以暂时不清楚项目本身有什么问题

**Comment by truebit** [comment]
那你用iconv这类的工具对xcodproj里面的project.pbxproj文件转换成utf8试试吧。不过要先知道它本来是什么编码。

Sent from my mobile device.

**Comment by DreamParagon** [comment]
好的，感谢您的建议，我从同事那里又拷贝一份正常的项目。。。因为我看pbxproj文件头部确实标注的utf8编码，所以正向您说的，可能项目文件本身哪里出现了问题。。
