### ISSUE TITLE
执行脚本后，虽然做了排序，但是仍然有冲突的问题

### ISSUE THREAD

**Issue by jiew** [truebit/xUnique#44]
如题，在 pre-commit 中添加了执行脚本，但并没有解决冲突问题，还是我的理解有误，这个工具并不是为了解决冲突问题，而只是为了更方便的手动修改 <<<< 和 ==== 标识的？

**Comment by truebit** [comment]
参考这个issue：https://github.com/truebit/xUnique/issues/26#issuecomment-161174466
