### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by shannonchou** [truebit/xUnique#5]
Uniquify and Sort
Traceback (most recent call last):
  File "./scripts2/xUnique.py", line 485, in <module>
    main(sys_argv)
  File "./scripts2/xUnique.py", line 466, in main
    xunique.unique_project()
  File "./scripts2/xUnique.py", line 154, in unique_project
    self.replace_uuids_with_file()
  File "./scripts2/xUnique.py", line 179, in replace_uuids_with_file
    print(new_line, end='')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-41: ordinal not in range(128)

**Comment by ZSaberLv0** [comment]
```
Uniquify and Sort
Traceback (most recent call last):
  File "xUnique/xUnique.py", line 566, in <module>
    main()
  File "xUnique/xUnique.py", line 546, in main
    xunique.unique_project()
  File "xUnique/xUnique.py", line 188, in unique_project
    self.__unique_project(self.root_hex)
  File "xUnique/xUnique.py", line 365, in __unique_project
    self.__set_to_result(project_hex, target_hex, cur_path_key)
  File "xUnique/xUnique.py", line 141, in __set_to_result
    current_path = '/'.join([str(current_node[i]) for i in current_path_key])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

same problem with the latest xUnique, any way to solve this?

**Comment by truebit** [comment]
could you send me your pbxproj file to my email? You can find it in license
file.

2016年6月13日星期一，ZERO <notifications@github.com> 写道：

> Uniquify and Sort
> Traceback (most recent call last):
>   File "xUnique/xUnique.py", line 566, in <module>
>     main()
>   File "xUnique/xUnique.py", line 546, in main
>     xunique.unique_project()
>   File "xUnique/xUnique.py", line 188, in unique_project
>     self.__unique_project(self.root_hex)
>   File "xUnique/xUnique.py", line 365, in __unique_project
>     self.__set_to_result(project_hex, target_hex, cur_path_key)
>   File "xUnique/xUnique.py", line 141, in __set_to_result
>     current_path = '/'.join([str(current_node[i]) for i in current_path_key])
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
>
> same problem with the latest xUnique, any way to solve this?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/truebit/xUnique/issues/5#issuecomment-225515169>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAuE2o5MYwNLTnklOHeEPM-4XIe8PZjQks5qLREUgaJpZM4CcjZk>
> .
>


-- 
Br,

Sean Wang
Blog: fclef.wordpress.com <http://fclef.wordpress.com/about>

**Comment by ZSaberLv0** [comment]
@truebit pbxproj sent to your email with no reply

**Comment by truebit** [comment]
Sorry, I am busy these days. Will look into it on this weekend

**Comment by truebit** [comment]
I executed with latest xunique, I got KeyError instead of UnicodeEncodeError

**Comment by ZSaberLv0** [comment]
sorry for that, the xcodeproj file was accidently added to the pbxproj file, remove all of them, and run xUnique again, the UnicodeEncodeError occurrs

**Comment by truebit** [comment]
ehh.. Cannot understand what you mean. just send another one
