### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by truebit** [truebit/xUnique#6]
```
Traceback (most recent call last):
  File "/Users/seanwang/Documents/work/Dev/xUnique/xUnique.py", line 486, in <module>
    main(sys_argv)
  File "/Users/seanwang/Documents/work/Dev/xUnique/xUnique.py", line 468, in main
    xunique.sort_pbxproj(options.sort_pbx_fn_bool)
  File "/Users/seanwang/Documents/work/Dev/xUnique/xUnique.py", line 302, in sort_pbxproj
    lines.sort(key=lambda file_str: pbx_key_ptn.search(file_str).group(1))
  File "/Users/seanwang/Documents/work/Dev/xUnique/xUnique.py", line 302, in <lambda>
    lines.sort(key=lambda file_str: pbx_key_ptn.search(file_str).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

When trying to xUnique [project file in webkit](https://raw.githubusercontent.com/WebKit/webkit/master/Source/WebKit/WebKit.xcodeproj/project.pbxproj)

**Comment by evan0502** [comment]
I got the same problem.
![image](https://cloud.githubusercontent.com/assets/8966069/19306114/b725f158-90a6-11e6-8b0f-228823edafcb.png)

**Comment by truebit** [comment]
@evan0502 could you provide your project.xcodeproj file?

**Comment by evan0502** [comment]
@truebit [https://pan.baidu.com/s/1bpMIEM7](url) .

**Comment by truebit** [comment]
@evan0502 Xcode project file would indent with white spaces after `/* Begin PBX??? section */` line. But your project file removed all the indent based white spaces in line beginning. 

That's the root cause. You need to revert the white spaces you removed
